name: napari bindings
app_name: napari
description: napari bindings for streamdeck

# action IDs will correspond to custom actions in custom_actions.py
menus:
  # viewer
  viewer_menu:
    key_binds: 
      - key_id: 0
        action_id: streamdeck:toggle_dialview
        value: "toggle_dialview"
      - key_id: 1
        action_id: streamdeck:toggle_control_pages
        value: "toggle_control_pages"
      - key_id: 2
        action_id: napari:viewer:a
        value: ""
      - key_id: 3
        action_id: napari:viewer:a
        value: ""
      - key_id: 4
        action_id: napari:viewer:a
        value: ""
      - key_id: 5
        action_id: napari:viewer:a
        value: ""
      - key_id: 6
        action_id: napari:viewer:a
        value: ""
      - key_id: 7
        action_id: napari:viewer:a
        value: ""

    dial_binds:
      - dial_id: 0
        action_id: ""
        value: ""
      - dial_id: 1
        action_id: ""
        value: ""
      - dial_id: 2
        action_id: ""
        value: ""
      - dial_id: 4
        action_id: ""
        value: ""

  # labels
  labels_menu: 
    key_binds:
      - key_id: 0
        action_id: streamdeck:toggle_dialview
        value: "toggle_dialview"
      - key_id: 1
        action_id: streamdeck:toggle_control_pages
        value: "toggle_control_pages"
      - key_id: 2
        action_id: napari:labels:erase
        value: "erase"
      - key_id: 3
        action_id: napari:labels:paint
        value: "paint"
      - key_id: 4
        action_id: napari:labels:pan_zoom
        value: "pan_zoom"
      - key_id: 5
        action_id: napari:labels:pick
        value: "pick"
      - key_id: 6
        action_id: napari:labels:a
        value: ""
      - key_id: 7
        action_id: napari:labels:a
        value: ""