name: napari bindings
app name: napari
description: napari bindings for streamdeck
# action IDs will correspond to custom actions in custom_actions.py
key binds:
  viewer_menu: 
    - button_id: 2  
      action_id: napari:viewer:
    - button_id: 3  
      action_id: napari:viewer:
    - button_id: 4  
      action_id: napari:viewer:
    - button_id: 5  
      action_id: napari:viewer:
    - button_id: 6  
      action_id: napari:viewer:
    - button_id: 7  
      action_id: napari:viewer:
  labels_menu: 
    - button_id: 2  
      action_id: napari:labels:erase
    - button_id: 3  
      action_id: napari:labels:paint
    - button_id: 4  
      action_id: napari:labels:fill
    - button_id: 5  
      action_id: napari:labels:pan_zoom
    - button_id: 6  
      action_id: napari:labels:
    - button_id: 7  
      action_id: napari:labels:

